swagger: '2.0'
info:
  title: Veeva Query
  description: Connect to Veeva Vault to run custom queries
  version: '1.0'
host: '@environmentVariables("new_veevavaultdomain")'
basePath: /api
schemes:
  - https
consumes: []
produces: []
paths:
  /v23.1/query:
    post:
      responses:
        default:
          description: default
          schema: {}
      summary: Veeva Query
      operationId: VeevaQuery
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                title: Username
                x-ms-visibility: important
              password:
                type: string
                title: Password
                x-ms-visibility: important
                format: password
              q:
                type: string
                description: Enter a VQL Query
                title: VQL Query
            required:
              - username
              - password
              - q
      description: Query Veeva Vault using VQL
definitions: {}
parameters: {}
responses: {}
securityDefinitions: {}
tags: []
security: []